sudo: false

language: node_js
node_js:
  - "stable"

deploy:
  provider: heroku
  app: "telephone-verify"
  api_key:
    secure: "aee1211a-1d16-4114-9c3c-76625cbbefe9"

branches:
  only:
    - master